version: '3'
name: trial-django
services:
  app:
    hostname: app
    build:
      context: "./container/app"
    env_file:
      - ".env"
    tty: true
    volumes:
      - "./containers/app/code/:/code/"
      - "./containers/app/data/:/data/"
  web:
    hostname: web
    build:
      context: "./container/nginx"
    env_file:
      - ".env"
    tty: true
    volumes:
      - "./container/app/data/:/data/"
    depends_on:
      - app
  sphinx:
    image: sphinxdoc/sphinx
    tty: true
    volumes:
      - "./docs/:/docs/"
    profiles:
      - dev_tool
  vscode:
    image: ahmadnassri/vscode-server
    profiles:
      - dev_tool
  pycharm:
    image: rycus86/pycharm
    profiles:
      - dev_tool
