version: "3"
name: trial-django
services:
  app:
    hostname: app
    extends:
      service: common
      file: docker-compose-common.yml
    build:
      context: ./containers/app
    user: ${PGID:-1000}:${PUID:-1000}
    env_file:
      - .env
    environment:
      - DEBUG=${DEBUG:-True}
    ports:
      - "8000:8000"
  web:
    hostname: web
    build:
      context: ./containers/nginx
    env_file:
      - .env
    ports:
      - "80:80"
    depends_on:
      - app
  vscode:
    hostname: vscode
    extends:
      service: common
      file: docker-compose-common.yml
    image: lscr.io/linuxserver/code-server:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID:-"1000"}
      - PGID=${PGID:-"1000"}
      - TZ=Asia/Tokyo
      - PASSWORD=password                   #optional
      - HASHED_PASSWORD=                    #optional
      - SUDO_PASSWORD=password              #optional
      - SUDO_PASSWORD_HASH=                 #optional
      - PROXY_DOMAIN=code-server.my.domain  #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    ports:
      - "3000:8443"
    volumes:
      - /home/${USER}/workspace/config/:/config/
    profiles:
      - dev_tool
  openvscode:
    hostname: openvscode
    extends:
      service: common
      file: docker-compose-common.yml
    image: lscr.io/linuxserver/openvscode-server:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID:-"1000"}
      - PGID=${PGID:-"1000"}
      - TZ=Asia/Tokyo
      - CONNECTION_TOKEN=       #optional
      - CONNECTION_SECRET=      #optional
      - SUDO_PASSWORD=password  #optional
      - SUDO_PASSWORD_HASH=     #optional
    ports:
      - "3000:3000"
    volumes:
      - /home/${USER}/workspace/config/:/config/
    profiles:
      - dev_tool
  obsidian:
    hostname: obsidian
    extends:
      service: common
      file: docker-compose-common.yml
    image: lscr.io/linuxserver/obsidian:latest
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined #optional
    shm_size: "1gb"
    environment:
      - PUID=${PUID:-"1000"}
      - PGID=${PGID:-"1000"}
      - TZ=Asia/Tokyo
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - /home/${USER}/workspace/config/:/config/
    devices:
      - /dev/dri:/dev/dri #optional
    profiles:
      - dev_tool
  sphinx:
    image: sphinxdoc/sphinx
    volumes:
      - ./docs/:/docs/
    profiles:
      - dev_tool
