version: "3"
name: trial-django
services:
  app:
    hostname: app
    build:
      context: ./containers/app
    env_file:
      - .env
    environment:
      - PUID=${PUID:-"20000"}
      - PGID=${PGID:-"20000"}
      - DEBUG=${DEBUG:-True}
    ports:
      - "8000:8000"
    volumes:
      - ./containers/app/code/:/code/
      - ./containers/app/data/:/data/
    tty: true
  web:
    hostname: web
    build:
      context: ./containers/nginx
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - ./containers/app/data/:/data/
    depends_on:
      - app
  vscode:
    hostname: vscode
    image: linuxserver/code-server:latest
    environment:
      - PUID=${PUID:-"20000"}
      - PGID=${PGID:-"20000"}
      - TZ=Asia/Tokyo
      - PASSWORD=password                   #optional
      - HASHED_PASSWORD=                    #optional
      - SUDO_PASSWORD=password              #optional
      - SUDO_PASSWORD_HASH=                 #optional
      - PROXY_DOMAIN=code-server.my.domain  #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    ports:
      - "3000:8443"
    volumes:
      - /home/${USER}/vscode/:/config/
      - ./containers/app/code/:/code/
      - ./containers/app/data/:/data/
    restart: unless-stopped
    profiles:
      - dev_tool
  openvscode:
    hostname: openvscode
    image: linuxserver/openvscode-server:latest
    environment:
      - PUID=${PUID:-"20000"}
      - PGID=${PGID:-"20000"}
      - TZ=Asia/Tokyo
      - CONNECTION_TOKEN=       #optional
      - CONNECTION_SECRET=      #optional
      - SUDO_PASSWORD=password  #optional
      - SUDO_PASSWORD_HASH=     #optional
    ports:
      - "3000:3000"
    volumes:
      - /home/${USER}/openvscode/:/config/
      - ./containers/app/code/:/code/
      - ./containers/app/data/:/data/
    restart: unless-stopped
    profiles:
      - dev_tool
  obsidian:
    hostname: obsidian
    image: linuxserver/obsidian:latest
    environment:
      - PUID=${PUID:-"20000"}
      - PGID=${PGID:-"20000"}
      - TZ=Asia/Tokyo
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - /home/${USER}/:/config/
      - /home/${USER}/obsidian/:/config/
      - ./containers/app/code/:/code/
      - ./containers/app/data/:/data/
    devices:
      - /dev/dri:/dev/dri #optional
    security_opt:
      - seccomp:unconfined #optional
    shm_size: "1gb"
    restart: unless-stopped
    profiles:
      - dev_tool
  sphinx:
    image: sphinxdoc/sphinx
    volumes:
      - ./containers/app/code/:/code/
      - ./docs/:/docs/
    profiles:
      - dev_tool
