FROM nginx:1.27.4-alpine
LABEL maintainer="Takamatsu Makoto <tkmtmkt@gmail.com>"

COPY ./docker/nginx/etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf
COPY ./docker/nginx/etc/ssl/private/ /etc/ssl/private/
